# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{redwood}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mark Wunsch"]
  s.date = %q{2010-04-12}
  s.default_executable = %q{redwood}
  s.description = %q{A simple library to create and manage basic tree-esque structures.}
  s.email = ["mark@markwunsch.com"]
  s.executables = ["redwood"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.md",
     "Rakefile",
     "bin/redwood",
     "lib/redwood.rb",
     "lib/redwood/filenode.rb",
     "lib/redwood/node.rb",
     "man/redwood.1",
     "man/redwood.1.html",
     "man/redwood.1.ronn",
     "redwood.gemspec",
     "test/helper.rb",
     "test/test_redwood.rb"
  ]
  s.homepage = %q{http://github.com/mwunsch/redwood}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby trees}
  s.test_files = [
    "test/helper.rb",
     "test/test_redwood.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, [">= 0.9.19"])
    else
      s.add_dependency(%q<bundler>, [">= 0.9.19"])
    end
  else
    s.add_dependency(%q<bundler>, [">= 0.9.19"])
  end
end

